spring:
 application:
   name: lbeurekaservice
   
server:
  port: 8761


eureka:

 client:

  registerWithEureka: false

  fetchRegistry: false
 instance:
   hostname: localhost
 server:
  
  wait-time-in-ms-when-sync-empty: 0

