spring:
  application:
    name: UserManagement

  datasource:
    url: jdbc:postgresql://localhost:5432/safesecureserene?useSSL=false&serverTimezone=UTC
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update  # Consider changing to 'validate' or 'none' in production
    show-sql: true
    dialect: org.hibernate.dialect.MySQL8Dialect

  cloud:
    gateway:
      mvc:
        routes:
          - id: lbservice-route
            uri: lb://FOODNWASTE
            predicates:
              - Path=/api/foodnwaste/**


          - id: lbservice2-route
            uri: lb://GADGETS
            predicates:
               - Path=/api/gadgets/**

    discovery:
      enabled: true

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

      instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${instanceId:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9999

#logging:
#  level:
#    org.springframework: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000

